### ISSUE TITLE
Offer a list of colors currently used on the layout

### ISSUE THREAD

**Issue by FroggieFrog** [AgmasGold/anno-designer#54]
issue migrated from [https://github.com/JcBernack/anno-designer/issues/16](https://github.com/JcBernack/anno-designer/issues/16)

- Display colors as filled rectangles?
- Display colors as raw values? ARGB or HEX or both?
- Display list of colors in statistics view?
I think best would be to wait till PR #23 is merged.
- Display list of colors on exported image?
- List of colors in current layout available via color picker?

**Comment by StingMcRay** [comment]
1 : Unknown
2 : ARGB : because that's the how the file would be: and only in advanced the HEX is visible (that can be set as we can set the ARGB as value
3 : I don't think that would be a thing 
4 : You can do that, however i don't this that's very important
5 : Layouts should be visible on the Building Setting or... In the menu as Color Layouts > <Layout list>
NOTE: On all of above we should see what Agmas thing abt that 
Maybe handy to come to Discord, that would speak better :)

**Comment by AgmasGold** [comment]
currently awaiting completion of PR #75
